In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
coordinates = pd.read_csv('./Inputs/es.csv', header = 0)
coordinates.sort_values(by='population_proper', ascending=False)

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Madrid,40.4169,-3.7033,Spain,ES,Madrid,primary,6211000,3266126
1,Barcelona,41.3825,2.1769,Spain,ES,Catalonia,admin,4800000,1620343
4,Valencia,39.4700,-0.3764,Spain,ES,Valencia,admin,792492,792492
2,Sevilla,37.2400,-5.9900,Spain,ES,Andalusia,admin,1100000,681998
6,Zaragoza,41.6500,-0.8833,Spain,ES,Aragon,admin,675301,673010
...,...,...,...,...,...,...,...,...,...
261,Benisanó,39.6133,-0.5753,Spain,ES,Valencia,NaN,2345,2345
262,Benirredrá,38.9611,-0.1919,Spain,ES,Valencia,NaN,1548,1548
263,El Puente del Arzobispo,39.8000,-5.1667,Spain,ES,Castille-La Mancha,NaN,1190,1153
264,Palmera,38.9417,-0.1517,Spain,ES,Valencia,NaN,1040,1040
265,Hortaleza,40.4667,-3.6333,Spain,ES,Madrid,NaN,1039,1039

In [3]:
padron = pd.DataFrame ()
headers = [2,2,1,2,1,1,1,1,1,1]
aux = pd.read_excel('./Inputs/Padron/pobmun14.xlsx', header = headers[0])
padron['CPRO'] = str (aux['CPRO'])
padron['Provincia'] = aux['PROVINCIA']
padron ['CMUN'] = str (aux['CMUN'])
# for i in range (15, 24):
#     name = './Inputs/Padron/pobmun' + str (i) + '.xlsx'
#     aux = pd.read_excel(name, header = 1, skiprows = 0)
#     padron_2023

In [4]:
piramide = pd.read_csv('./Inputs/PirámidePoblacion_Provincias.csv', header=0, delimiter = ';')
piramide

C:\Users\david\.anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Provincias,Edad (grupos quinquenales),Españoles/Extranjeros,Sexo,Año,Total
0,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2022,"47,475,420"
1,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2021,"47,385,107"
2,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2020,"47,450,795"
3,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2019,"47,026,208"
4,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2018,"46,722,980"
...,...,...,...,...,...,...
262345,52 Melilla,100 años y más,Extranjeros,Mujeres,2002,1
262346,52 Melilla,100 años y más,Extranjeros,Mujeres,2001,1
262347,52 Melilla,100 años y más,Extranjeros,Mujeres,2000,1
262348,52 Melilla,100 años y más,Extranjeros,Mujeres,1999,0
262349,52 Melilla,100 años y más,Extranjeros,Mujeres,1998,1

In [5]:
total = piramide[piramide['Edad (grupos quinquenales)'] == 'TOTAL EDADES']
total = total[total['Españoles/Extranjeros'] == 'TOTAL']
filtered = total[total['Sexo'] == 'Ambos sexos']
filtered

,Provincias,Edad (grupos quinquenales),Españoles/Extranjeros,Sexo,Año,Total
0,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2022,"47,475,420"
1,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2021,"47,385,107"
2,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2020,"47,450,795"
3,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2019,"47,026,208"
4,TOTAL ESPAÑA,TOTAL EDADES,TOTAL,Ambos sexos,2018,"46,722,980"
...,...,...,...,...,...,...
257420,52 Melilla,TOTAL EDADES,TOTAL,Ambos sexos,2002,"69,184"
257421,52 Melilla,TOTAL EDADES,TOTAL,Ambos sexos,2001,"68,789"
257422,52 Melilla,TOTAL EDADES,TOTAL,Ambos sexos,2000,"66,263"
257423,52 Melilla,TOTAL EDADES,TOTAL,Ambos sexos,1999,"56,929"
257424,52 Melilla,TOTAL EDADES,TOTAL,Ambos sexos,1998,"60,108"

In [6]:
provincias = np.unique (filtered['Provincias'])
provincias

array(['01 Araba/Álava', '02 Albacete', '03 Alicante/Alacant',
       '04 Almería', '05 Ávila', '06 Badajoz', '07 Balears, Illes',
       '08 Barcelona', '09 Burgos', '10 Cáceres', '11 Cádiz',
       '12 Castellón/Castelló', '13 Ciudad Real', '14 Córdoba',
       '15 Coruña, A', '16 Cuenca', '17 Girona', '18 Granada',
       '19 Guadalajara', '20 Gipuzkoa', '21 Huelva', '22 Huesca',
       '23 Jaén', '24 León', '25 Lleida', '26 Rioja, La', '27 Lugo',
       '28 Madrid', '29 Málaga', '30 Murcia', '31 Navarra', '32 Ourense',
       '33 Asturias', '34 Palencia', '35 Palmas, Las', '36 Pontevedra',
       '37 Salamanca', '38 Santa Cruz de Tenerife', '39 Cantabria',
       '40 Segovia', '41 Sevilla', '42 Soria', '43 Tarragona',
       '44 Teruel', '45 Toledo', '46 Valencia/València', '47 Valladolid',
       '48 Bizkaia', '49 Zamora', '50 Zaragoza', '51 Ceuta', '52 Melilla',
       'TOTAL ESPAÑA'], dtype=object)

In [7]:
poblaciones = {}
for año in range (2014,2023):
    aux = []
    for provincia in provincias:
        print (año, provincia)
        row = filtered[(filtered['Provincias'] == provincia) & (filtered['Año'] == año)].index
        print (row)
        aux1 = filtered['Total'][row[0]].replace(',', '')
        print (aux1)
        aux.append(int(aux1))
    poblaciones[str(año)] = aux

2014 01 Araba/Álava
Int64Index([19808], dtype='int64')
321932
2014 02 Albacete
Int64Index([4958], dtype='int64')
396987
2014 03 Alicante/Alacant
Int64Index([9908], dtype='int64')
1868438
2014 04 Almería
Int64Index([14858], dtype='int64')
701688
2014 05 Ávila
Int64Index([29708], dtype='int64')
167015
2014 06 Badajoz
Int64Index([34658], dtype='int64')
690929
2014 07 Balears, Illes
Int64Index([39608], dtype='int64')
1103442
2014 08 Barcelona
Int64Index([44558], dtype='int64')
5523784
2014 09 Burgos
Int64Index([54458], dtype='int64')
366900
2014 10 Cáceres
Int64Index([59408], dtype='int64')
408703
2014 11 Cádiz
Int64Index([64358], dtype='int64')
1240175
2014 12 Castellón/Castelló
Int64Index([74258], dtype='int64')
587508
2014 13 Ciudad Real
Int64Index([79208], dtype='int64')
519613
2014 14 Córdoba
Int64Index([84158], dtype='int64')
799402
2014 15 Coruña, A
Int64Index([89108], dtype='int64')
1132735
2014 16 Cuenca
Int64Index([94058], dtype='int64')
207449
2014 17 Girona
Int64Index([103958], dtype='int64')
756156
2014 18 Granada
Int64Index([108908], dtype='int64')
919455
2014 19 Guadalajara
Int64Index([113858], dtype='int64')
255426
2014 20 Gipuzkoa
Int64Index([99008], dtype='int64')
715148
2014 21 Huelva
Int64Index([118808], dtype='int64')
519229
2014 22 Huesca
Int64Index([123758], dtype='int64')
224909
2014 23 Jaén
Int64Index([128708], dtype='int64')
659033
2014 24 León
Int64Index([133658], dtype='int64')
484694
2014 25 Lleida
Int64Index([138608], dtype='int64')
438001
2014 26 Rioja, La
Int64Index([188108], dtype='int64')
319002
2014 27 Lugo
Int64Index([143558], dtype='int64')
342748
2014 28 Madrid
Int64Index([148508], dtype='int64')
6454440
2014 29 Málaga
Int64Index([153458], dtype='int64')
1621968
2014 30 Murcia
Int64Index([158408], dtype='int64')
1466818
2014 31 Navarra
Int64Index([163358], dtype='int64')
640790
2014 32 Ourense
Int64Index([168308], dtype='int64')
322293
2014 33 Asturias
Int64Index([24758], dtype='int64')
1061756
2014 34 Palencia
Int64Index([173258], dtype='int64')
167609
2014 35 Palmas, Las
Int64Index([178208], dtype='int64')
1100027
2014 36 Pontevedra
Int64Index([183158], dtype='int64')
950919
2014 37 Salamanca
Int64Index([193058], dtype='int64')
342459
2014 38 Santa Cruz de Tenerife
Int64Index([198008], dtype='int64')
1004788
2014 39 Cantabria
Int64Index([69308], dtype='int64')
588656
2014 40 Segovia
Int64Index([202958], dtype='int64')
159303
2014 41 Sevilla
Int64Index([207908], dtype='int64')
1941355
2014 42 Soria
Int64Index([212858], dtype='int64')
92221
2014 43 Tarragona
Int64Index([217808], dtype='int64')
800962
2014 44 Teruel
Int64Index([222758], dtype='int64')
140365
2014 45 Toledo
Int64Index([227708], dtype='int64')
699136
2014 46 Valencia/València
Int64Index([232658], dtype='int64')
2548898
2014 47 Valladolid
Int64Index([237608], dtype='int64')
529157
2014 48 Bizkaia
Int64Index([49508], dtype='int64')
1151905
2014 49 Zamora
Int64Index([242558], dtype='int64')
185432
2014 50 Zaragoza
Int64Index([247508], dtype='int64')
960111
2014 51 Ceuta
Int64Index([252458], dtype='int64')
84963
2014 52 Melilla
Int64Index([257408], dtype='int64')
84509
2014 TOTAL ESPAÑA
Int64Index([8], dtype='int64')
46771341
2015 01 Araba/Álava
Int64Index([19807], dtype='int64')
323648
2015 02 Albacete
Int64Index([4957], dtype='int64')
394580
2015 03 Alicante/Alacant
Int64Index([9907], dtype='int64')
1855047
2015 04 Almería
Int64Index([14857], dtype='int64')
701211
2015 05 Ávila
Int64Index([29707], dtype='int64')
164925
2015 06 Badajoz
Int64Index([34657], dtype='int64')
686730
2015 07 Balears, Illes
Int64Index([39607], dtype='int64')
1104479
2015 08 Barcelona
Int64Index([44557], dtype='int64')
5523922
2015 09 Burgos
Int64Index([54457], dtype='int64')
364002
2015 10 Cáceres
Int64Index([59407], dtype='int64')
406267
2015 11 Cádiz
Int64Index([64357], dtype='int64')
1240284
2015 12 Castellón/Castelló
Int64Index([74257], dtype='int64')
582327
2015 13 Ciudad Real
Int64Index([79207], dtype='int64')
513713
2015 14 Córdoba
Int64Index([84157], dtype='int64')
795611
2015 15 Coruña, A
Int64Index([89107], dtype='int64')
1127196
2015 16 Cuenca
Int64Index([94057], dtype='int64')
203841
2015 17 Girona
Int64Index([103957], dtype='int64')
753054
2015 18 Granada
Int64Index([108907], dtype='int64')
917297
2015 19 Guadalajara
Int64Index([113857], dtype='int64')
253686
2015 20 Gipuzkoa
Int64Index([99007], dtype='int64')
716834
2015 21 Huelva
Int64Index([118807], dtype='int64')
520017
2015 22 Huesca
Int64Index([123757], dtype='int64')
222909
2015 23 Jaén
Int64Index([128707], dtype='int64')
654170
2015 24 León
Int64Index([133657], dtype='int64')
479395
2015 25 Lleida
Int64Index([138607], dtype='int64')
436029
2015 26 Rioja, La
Int64Index([188107], dtype='int64')
317053
2015 27 Lugo
Int64Index([143557], dtype='int64')
339386
2015 28 Madrid
Int64Index([148507], dtype='int64')
6436996
2015 29 Málaga
Int64Index([153457], dtype='int64')
1628973
2015 30 Murcia
Int64Index([158407], dtype='int64')
1467288
2015 31 Navarra
Int64Index([163357], dtype='int64')
640476
2015 32 Ourense
Int64Index([168307], dtype='int64')
318391
2015 33 Asturias
Int64Index([24757], dtype='int64')
1051229
2015 34 Palencia
Int64Index([173257], dtype='int64')
166035
2015 35 Palmas, Las
Int64Index([178207], dtype='int64')
1098406
2015 36 Pontevedra
Int64Index([183157], dtype='int64')
947374
2015 37 Salamanca
Int64Index([193057], dtype='int64')
339395
2015 38 Santa Cruz de Tenerife
Int64Index([198007], dtype='int64')
1001900
2015 39 Cantabria
Int64Index([69307], dtype='int64')
585179
2015 40 Segovia
Int64Index([202957], dtype='int64')
157570
2015 41 Sevilla
Int64Index([207907], dtype='int64')
1941480
2015 42 Soria
Int64Index([212857], dtype='int64')
91006
2015 43 Tarragona
Int64Index([217807], dtype='int64')
795101
2015 44 Teruel
Int64Index([222757], dtype='int64')
138932
2015 45 Toledo
Int64Index([227707], dtype='int64')
693371
2015 46 Valencia/València
Int64Index([232657], dtype='int64')
2543315
2015 47 Valladolid
Int64Index([237607], dtype='int64')
526288
2015 48 Bizkaia
Int64Index([49507], dtype='int64')
1148775
2015 49 Zamora
Int64Index([242557], dtype='int64')
183436
2015 50 Zaragoza
Int64Index([247507], dtype='int64')
956006
2015 51 Ceuta
Int64Index([252457], dtype='int64')
84263
2015 52 Melilla
Int64Index([257407], dtype='int64')
85584
2015 TOTAL ESPAÑA
Int64Index([7], dtype='int64')
46624382
2016 01 Araba/Álava
Int64Index([19806], dtype='int64')
324126
2016 02 Albacete
Int64Index([4956], dtype='int64')
392118
2016 03 Alicante/Alacant
Int64Index([9906], dtype='int64')
1836459
2016 04 Almería
Int64Index([14856], dtype='int64')
704297
2016 05 Ávila
Int64Index([29706], dtype='int64')
162514
2016 06 Badajoz
Int64Index([34656], dtype='int64')
684113
2016 07 Balears, Illes
Int64Index([39606], dtype='int64')
1107220
2016 08 Barcelona
Int64Index([44556], dtype='int64')
5542680
2016 09 Burgos
Int64Index([54456], dtype='int64')
360995
2016 10 Cáceres
Int64Index([59406], dtype='int64')
403665
2016 11 Cádiz
Int64Index([64356], dtype='int64')
1239889
2016 12 Castellón/Castelló
Int64Index([74256], dtype='int64')
579245
2016 13 Ciudad Real
Int64Index([79206], dtype='int64')
506888
2016 14 Córdoba
Int64Index([84156], dtype='int64')
791610
2016 15 Coruña, A
Int64Index([89106], dtype='int64')
1122799
2016 16 Cuenca
Int64Index([94056], dtype='int64')
201071
2016 17 Girona
Int64Index([103956], dtype='int64')
753576
2016 18 Granada
Int64Index([108906], dtype='int64')
915392
2016 19 Guadalajara
Int64Index([113856], dtype='int64')
252882
2016 20 Gipuzkoa
Int64Index([99006], dtype='int64')
717832
2016 21 Huelva
Int64Index([118806], dtype='int64')
519596
2016 22 Huesca
Int64Index([123756], dtype='int64')
221079
2016 23 Jaén
Int64Index([128706], dtype='int64')
648250
2016 24 León
Int64Index([133656], dtype='int64')
473604
2016 25 Lleida
Int64Index([138606], dtype='int64')
434041
2016 26 Rioja, La
Int64Index([188106], dtype='int64')
315794
2016 27 Lugo
Int64Index([143556], dtype='int64')
336527
2016 28 Madrid
Int64Index([148506], dtype='int64')
6466996
2016 29 Málaga
Int64Index([153456], dtype='int64')
1629298
2016 30 Murcia
Int64Index([158406], dtype='int64')
1464847
2016 31 Navarra
Int64Index([163356], dtype='int64')
640647
2016 32 Ourense
Int64Index([168306], dtype='int64')
314853
2016 33 Asturias
Int64Index([24756], dtype='int64')
1042608
2016 34 Palencia
Int64Index([173256], dtype='int64')
164644
2016 35 Palmas, Las
Int64Index([178206], dtype='int64')
1097800
2016 36 Pontevedra
Int64Index([183156], dtype='int64')
944346
2016 37 Salamanca
Int64Index([193056], dtype='int64')
335985
2016 38 Santa Cruz de Tenerife
Int64Index([198006], dtype='int64')
1004124
2016 39 Cantabria
Int64Index([69306], dtype='int64')
582206
2016 40 Segovia
Int64Index([202956], dtype='int64')
155652
2016 41 Sevilla
Int64Index([207906], dtype='int64')
1939775
2016 42 Soria
Int64Index([212856], dtype='int64')
90040
2016 43 Tarragona
Int64Index([217806], dtype='int64')
792299
2016 44 Teruel
Int64Index([222756], dtype='int64')
136977
2016 45 Toledo
Int64Index([227706], dtype='int64')
688672
2016 46 Valencia/València
Int64Index([232656], dtype='int64')
2544264
2016 47 Valladolid
Int64Index([237606], dtype='int64')
523679
2016 48 Bizkaia
Int64Index([49506], dtype='int64')
1147576
2016 49 Zamora
Int64Index([242556], dtype='int64')
180406
2016 50 Zaragoza
Int64Index([247506], dtype='int64')
950507
2016 51 Ceuta
Int64Index([252456], dtype='int64')
84519
2016 52 Melilla
Int64Index([257406], dtype='int64')
86026
2016 TOTAL ESPAÑA
Int64Index([6], dtype='int64')
46557008
2017 01 Araba/Álava
Int64Index([19805], dtype='int64')
326574
2017 02 Albacete
Int64Index([4955], dtype='int64')
390032
2017 03 Alicante/Alacant
Int64Index([9905], dtype='int64')
1825332
2017 04 Almería
Int64Index([14855], dtype='int64')
706672

2017 05 Ávila
Int64Index([29705], dtype='int64')
160700
2017 06 Badajoz
Int64Index([34655], dtype='int64')
679884
2017 07 Balears, Illes
Int64Index([39605], dtype='int64')
1115999
2017 08 Barcelona
Int64Index([44555], dtype='int64')
5576037
2017 09 Burgos
Int64Index([54455], dtype='int64')
358171
2017 10 Cáceres
Int64Index([59405], dtype='int64')
400036
2017 11 Cádiz
Int64Index([64355], dtype='int64')
1239435
2017 12 Castellón/Castelló
Int64Index([74255], dtype='int64')
575470
2017 13 Ciudad Real
Int64Index([79205], dtype='int64')
502578
2017 14 Córdoba
Int64Index([84155], dtype='int64')
788219
2017 15 Coruña, A
Int64Index([89105], dtype='int64')
1120294
2017 16 Cuenca
Int64Index([94055], dtype='int64')
198718
2017 17 Girona
Int64Index([103955], dtype='int64')
755716
2017 18 Granada
Int64Index([108905], dtype='int64')
912938
2017 19 Guadalajara
Int64Index([113855], dtype='int64')
253310
2017 20 Gipuzkoa
Int64Index([99005], dtype='int64')
719282
2017 21 Huelva
Int64Index([118805], dtype='int64')
518930
2017 22 Huesca
Int64Index([123755], dtype='int64')
219702
2017 23 Jaén
Int64Index([128705], dtype='int64')
643484
2017 24 León
Int64Index([133655], dtype='int64')
468316
2017 25 Lleida
Int64Index([138605], dtype='int64')
432384
2017 26 Rioja, La
Int64Index([188105], dtype='int64')
315381
2017 27 Lugo
Int64Index([143555], dtype='int64')
333634
2017 28 Madrid
Int64Index([148505], dtype='int64')
6507184
2017 29 Málaga
Int64Index([153455], dtype='int64')
1630615
2017 30 Murcia
Int64Index([158405], dtype='int64')
1470273
2017 31 Navarra
Int64Index([163355], dtype='int64')
643234
2017 32 Ourense
Int64Index([168305], dtype='int64')
311680
2017 33 Asturias
Int64Index([24755], dtype='int64')
1034960
2017 34 Palencia
Int64Index([173255], dtype='int64')
163390
2017 35 Palmas, Las
Int64Index([178205], dtype='int64')
1100480
2017 36 Pontevedra
Int64Index([183155], dtype='int64')
942731
2017 37 Salamanca
Int64Index([193055], dtype='int64')
333603
2017 38 Santa Cruz de Tenerife
Int64Index([198005], dtype='int64')
1007641
2017 39 Cantabria
Int64Index([69305], dtype='int64')
580295
2017 40 Segovia
Int64Index([202955], dtype='int64')
154184
2017 41 Sevilla
Int64Index([207905], dtype='int64')
1939527
2017 42 Soria
Int64Index([212855], dtype='int64')
88903
2017 43 Tarragona
Int64Index([217805], dtype='int64')
791693
2017 44 Teruel
Int64Index([222755], dtype='int64')
135562
2017 45 Toledo
Int64Index([227705], dtype='int64')
686841
2017 46 Valencia/València
Int64Index([232655], dtype='int64')
2540707
2017 47 Valladolid
Int64Index([237605], dtype='int64')
521130
2017 48 Bizkaia
Int64Index([49505], dtype='int64')
1148302
2017 49 Zamora
Int64Index([242555], dtype='int64')
177404
2017 50 Zaragoza
Int64Index([247505], dtype='int64')
953486
2017 51 Ceuta
Int64Index([252455], dtype='int64')
84959
2017 52 Melilla
Int64Index([257405], dtype='int64')
86120
2017 TOTAL ESPAÑA
Int64Index([5], dtype='int64')
46572132
2018 01 Araba/Álava
Int64Index([19804], dtype='int64')
328868
2018 02 Albacete
Int64Index([4954], dtype='int64')
388786
2018 03 Alicante/Alacant
Int64Index([9904], dtype='int64')
1838819
2018 04 Almería
Int64Index([14854], dtype='int64')
709340
2018 05 Ávila
Int64Index([29704], dtype='int64')
158498
2018 06 Badajoz
Int64Index([34654], dtype='int64')
676376
2018 07 Balears, Illes
Int64Index([39604], dtype='int64')
1128908
2018 08 Barcelona
Int64Index([44554], dtype='int64')
5609350
2018 09 Burgos
Int64Index([54454], dtype='int64')
357070
2018 10 Cáceres
Int64Index([59404], dtype='int64')
396487
2018 11 Cádiz
Int64Index([64354], dtype='int64')
1238714
2018 12 Castellón/Castelló
Int64Index([74254], dtype='int64')
576898
2018 13 Ciudad Real
Int64Index([79204], dtype='int64')
499100
2018 14 Córdoba
Int64Index([84154], dtype='int64')
785240
2018 15 Coruña, A
Int64Index([89104], dtype='int64')
1119351
2018 16 Cuenca
Int64Index([94054], dtype='int64')
197222
2018 17 Girona
Int64Index([103954], dtype='int64')
761947
2018 18 Granada
Int64Index([108904], dtype='int64')
912075
2018 19 Guadalajara
Int64Index([113854], dtype='int64')
254308
2018 20 Gipuzkoa
Int64Index([99004], dtype='int64')
720592
2018 21 Huelva
Int64Index([118804], dtype='int64')
519932
2018 22 Huesca
Int64Index([123754], dtype='int64')
219345
2018 23 Jaén
Int64Index([128704], dtype='int64')
638099
2018 24 León
Int64Index([133654], dtype='int64')
463746
2018 25 Lleida
Int64Index([138604], dtype='int64')
432866
2018 26 Rioja, La
Int64Index([188104], dtype='int64')
315675
2018 27 Lugo
Int64Index([143554], dtype='int64')
331327
2018 28 Madrid
Int64Index([148504], dtype='int64')
6578079
2018 29 Málaga
Int64Index([153454], dtype='int64')
1641121
2018 30 Murcia
Int64Index([158404], dtype='int64')
1478509
2018 31 Navarra
Int64Index([163354], dtype='int64')
647554
2018 32 Ourense
Int64Index([168304], dtype='int64')
309293
2018 33 Asturias
Int64Index([24754], dtype='int64')
1028244
2018 34 Palencia
Int64Index([173254], dtype='int64')
162035
2018 35 Palmas, Las
Int64Index([178204], dtype='int64')
1109175
2018 36 Pontevedra
Int64Index([183154], dtype='int64')
941772
2018 37 Salamanca
Int64Index([193054], dtype='int64')
331473
2018 38 Santa Cruz de Tenerife
Int64Index([198004], dtype='int64')
1018510
2018 39 Cantabria
Int64Index([69304], dtype='int64')
580229
2018 40 Segovia
Int64Index([202954], dtype='int64')
153342
2018 41 Sevilla
Int64Index([207904], dtype='int64')
1939887
2018 42 Soria
Int64Index([212854], dtype='int64')
88600
2018 43 Tarragona
Int64Index([217804], dtype='int64')
795902
2018 44 Teruel
Int64Index([222754], dtype='int64')
134572
2018 45 Toledo
Int64Index([227704], dtype='int64')
687391
2018 46 Valencia/València
Int64Index([232654], dtype='int64')
2547986
2018 47 Valladolid
Int64Index([237604], dtype='int64')
519851
2018 48 Bizkaia
Int64Index([49504], dtype='int64')
1149628
2018 49 Zamora
Int64Index([242554], dtype='int64')
174549
2018 50 Zaragoza
Int64Index([247504], dtype='int64')
954811
2018 51 Ceuta
Int64Index([252454], dtype='int64')
85144
2018 52 Melilla
Int64Index([257404], dtype='int64')
86384
2018 TOTAL ESPAÑA
Int64Index([4], dtype='int64')
46722980
2019 01 Araba/Álava
Int64Index([19803], dtype='int64')
331549
2019 02 Albacete
Int64Index([4953], dtype='int64')
388167
2019 03 Alicante/Alacant
Int64Index([9903], dtype='int64')
1858683
2019 04 Almería
Int64Index([14853], dtype='int64')
716820
2019 05 Ávila
Int64Index([29703], dtype='int64')
157640
2019 06 Badajoz
Int64Index([34653], dtype='int64')
673559
2019 07 Balears, Illes
Int64Index([39603], dtype='int64')
1149460
2019 08 Barcelona
Int64Index([44553], dtype='int64')
5664579
2019 09 Burgos
Int64Index([54453], dtype='int64')
356958
2019 10 Cáceres
Int64Index([59403], dtype='int64')
394151
2019 11 Cádiz
Int64Index([64353], dtype='int64')
1240155
2019 12 Castellón/Castelló
Int64Index([74253], dtype='int64')
579962
2019 13 Ciudad Real
Int64Index([79203], dtype='int64')
495761
2019 14 Córdoba
Int64Index([84153], dtype='int64')
782979
2019 15 Coruña, A
Int64Index([89103], dtype='int64')
1119596
2019 16 Cuenca
Int64Index([94053], dtype='int64')
196329
2019 17 Girona
Int64Index([103953], dtype='int64')
771044
2019 18 Granada
Int64Index([108903], dtype='int64')
914678
2019 19 Guadalajara
Int64Index([113853], dtype='int64')
257762
2019 20 Gipuzkoa
Int64Index([99003], dtype='int64')
723576
2019 21 Huelva
Int64Index([118803], dtype='int64')
521870
2019 22 Huesca
Int64Index([123753], dtype='int64')
220461
2019 23 Jaén
Int64Index([128703], dtype='int64')
633564
2019 24 León
Int64Index([133653], dtype='int64')
460001
2019 25 Lleida
Int64Index([138603], dtype='int64')
434930
2019 26 Rioja, La
Int64Index([188103], dtype='int64')
316798
2019 27 Lugo
Int64Index([143553], dtype='int64')
329587
2019 28 Madrid
Int64Index([148503], dtype='int64')
6663394
2019 29 Málaga
Int64Index([153453], dtype='int64')
1661785
2019 30 Murcia
Int64Index([158403], dtype='int64')
1493898
2019 31 Navarra
Int64Index([163353], dtype='int64')
654214
2019 32 Ourense
Int64Index([168303], dtype='int64')
307651
2019 33 Asturias
Int64Index([24753], dtype='int64')
1022800
2019 34 Palencia
Int64Index([173253], dtype='int64')
160980
2019 35 Palmas, Las
Int64Index([178203], dtype='int64')
1120406
2019 36 Pontevedra
Int64Index([183153], dtype='int64')
942665
2019 37 Salamanca
Int64Index([193053], dtype='int64')
330119
2019 38 Santa Cruz de Tenerife
Int64Index([198003], dtype='int64')
1032983
2019 39 Cantabria
Int64Index([69303], dtype='int64')
581078
2019 40 Segovia
Int64Index([202953], dtype='int64')
153129
2019 41 Sevilla
Int64Index([207903], dtype='int64')
1942389
2019 42 Soria
Int64Index([212853], dtype='int64')
88636
2019 43 Tarragona
Int64Index([217803], dtype='int64')
804664
2019 44 Teruel
Int64Index([222753], dtype='int64')
134137
2019 45 Toledo
Int64Index([227703], dtype='int64')
694844
2019 46 Valencia/València
Int64Index([232653], dtype='int64')
2565124
2019 47 Valladolid
Int64Index([237603], dtype='int64')
519546
2019 48 Bizkaia
Int64Index([49503], dtype='int64')
1152651
2019 49 Zamora
Int64Index([242553], dtype='int64')
172539
2019 50 Zaragoza
Int64Index([247503], dtype='int64')
964693
2019 51 Ceuta
Int64Index([252453], dtype='int64')
84777
2019 52 Melilla
Int64Index([257403], dtype='int64')
86487
2019 TOTAL ESPAÑA
Int64Index([3], dtype='int64')
47026208
2020 01 Araba/Álava
Int64Index([19802], dtype='int64')
333940
2020 02 Albacete
Int64Index([4952], dtype='int64')
388270
2020 03 Alicante/Alacant
Int64Index([9902], dtype='int64')
1879888
2020 04 Almería
Int64Index([14852], dtype='int64')
727945
2020 05 Ávila
Int64Index([29702], dtype='int64')
157664
2020 06 Badajoz
Int64Index([34652], dtype='int64')
672137
2020 07 Balears, Illes
Int64Index([39602], dtype='int64')
1171543
2020 08 Barcelona
Int64Index([44552], dtype='int64')
5743402
2020 09 Burgos
Int64Index([54452], dtype='int64')
357650
2020 10 Cáceres
Int64Index([59402], dtype='int64')
391850
2020 11 Cádiz
Int64Index([64352], dtype='int64')
1244049
2020 12 Castellón/Castelló
Int64Index([74252], dtype='int64')
585590
2020 13 Ciudad Real
Int64Index([79202], dtype='int64')
495045
2020 14 Córdoba
Int64Index([84152], dtype='int64')
781451
2020 15 Coruña, A
Int64Index([89102], dtype='int64')
1121815
2020 16 Cuenca
Int64Index([94052], dtype='int64')
196139
2020 17 Girona
Int64Index([103952], dtype='int64')
781788
2020 18 Granada
Int64Index([108902], dtype='int64')
919168
2020 19 Guadalajara
Int64Index([113852], dtype='int64')
261995
2020 20 Gipuzkoa
Int64Index([99002], dtype='int64')
727121
2020 21 Huelva
Int64Index([118802], dtype='int64')
524278
2020 22 Huesca
Int64Index([123752], dtype='int64')
222687
2020 23 Jaén
Int64Index([128702], dtype='int64')
631381
2020 24 León
Int64Index([133652], dtype='int64')
456439
2020 25 Lleida
Int64Index([138602], dtype='int64')
438517
2020 26 Rioja, La
Int64Index([188102], dtype='int64')
319914
2020 27 Lugo
Int64Index([143552], dtype='int64')
327946
2020 28 Madrid
Int64Index([148502], dtype='int64')
6779888
2020 29 Málaga
Int64Index([153452], dtype='int64')
1685920
2020 30 Murcia
Int64Index([158402], dtype='int64')
1511251
2020 31 Navarra
Int64Index([163352], dtype='int64')
661197
2020 32 Ourense

Int64Index([168302], dtype='int64')
306650
2020 33 Asturias
Int64Index([24752], dtype='int64')
1018784
2020 34 Palencia
Int64Index([173252], dtype='int64')
160321
2020 35 Palmas, Las
Int64Index([178202], dtype='int64')
1131065
2020 36 Pontevedra
Int64Index([183152], dtype='int64')
945408
2020 37 Salamanca
Int64Index([193052], dtype='int64')
329245
2020 38 Santa Cruz de Tenerife
Int64Index([198002], dtype='int64')
1044887
2020 39 Cantabria
Int64Index([69302], dtype='int64')
582905
2020 40 Segovia
Int64Index([202952], dtype='int64')
153478
2020 41 Sevilla
Int64Index([207902], dtype='int64')
1950219
2020 42 Soria
Int64Index([212852], dtype='int64')
88884
2020 43 Tarragona
Int64Index([217802], dtype='int64')
816772
2020 44 Teruel
Int64Index([222752], dtype='int64')
134176
2020 45 Toledo
Int64Index([227702], dtype='int64')
703772
2020 46 Valencia/València
Int64Index([232652], dtype='int64')
2591875
2020 47 Valladolid
Int64Index([237602], dtype='int64')
520649
2020 48 Bizkaia
Int64Index([49502], dtype='int64')
1159443
2020 49 Zamora
Int64Index([242552], dtype='int64')
170588
2020 50 Zaragoza
Int64Index([247502], dtype='int64')
972528
2020 51 Ceuta
Int64Index([252452], dtype='int64')
84202
2020 52 Melilla
Int64Index([257402], dtype='int64')
87076
2020 TOTAL ESPAÑA
Int64Index([2], dtype='int64')
47450795
2021 01 Araba/Álava
Int64Index([19801], dtype='int64')
333626
2021 02 Albacete
Int64Index([4951], dtype='int64')
386464
2021 03 Alicante/Alacant
Int64Index([9901], dtype='int64')
1881762
2021 04 Almería
Int64Index([14851], dtype='int64')
731792
2021 05 Ávila
Int64Index([29701], dtype='int64')
158421
2021 06 Badajoz
Int64Index([34651], dtype='int64')
669943
2021 07 Balears, Illes
Int64Index([39601], dtype='int64')
1173008
2021 08 Barcelona
Int64Index([44551], dtype='int64')
5714730
2021 09 Burgos
Int64Index([54451], dtype='int64')
356055
2021 10 Cáceres
Int64Index([59401], dtype='int64')
389558
2021 11 Cádiz
Int64Index([64351], dtype='int64')
1245960
2021 12 Castellón/Castelló
Int64Index([74251], dtype='int64')
587064
2021 13 Ciudad Real
Int64Index([79201], dtype='int64')
492591
2021 14 Córdoba
Int64Index([84151], dtype='int64')
776789
2021 15 Coruña, A
Int64Index([89101], dtype='int64')
1120134
2021 16 Cuenca
Int64Index([94051], dtype='int64')
195516
2021 17 Girona
Int64Index([103951], dtype='int64')
786596
2021 18 Granada
Int64Index([108901], dtype='int64')
921338
2021 19 Guadalajara
Int64Index([113851], dtype='int64')
265588
2021 20 Gipuzkoa
Int64Index([99001], dtype='int64')
726033
2021 21 Huelva
Int64Index([118801], dtype='int64')
525835
2021 22 Huesca
Int64Index([123751], dtype='int64')
224264
2021 23 Jaén
Int64Index([128701], dtype='int64')
627190
2021 24 León
Int64Index([133651], dtype='int64')
451706
2021 25 Lleida
Int64Index([138601], dtype='int64')
439727
2021 26 Rioja, La
Int64Index([188101], dtype='int64')
319796
2021 27 Lugo
Int64Index([143551], dtype='int64')
326013
2021 28 Madrid
Int64Index([148501], dtype='int64')
6751251
2021 29 Málaga
Int64Index([153451], dtype='int64')
1695651
2021 30 Murcia
Int64Index([158401], dtype='int64')
1518486
2021 31 Navarra
Int64Index([163351], dtype='int64')
661537
2021 32 Ourense
Int64Index([168301], dtype='int64')
305223
2021 33 Asturias
Int64Index([24751], dtype='int64')
1011792
2021 34 Palencia
Int64Index([173251], dtype='int64')
159123
2021 35 Palmas, Las
Int64Index([178201], dtype='int64')
1128539
2021 36 Pontevedra
Int64Index([183151], dtype='int64')
944275
2021 37 Salamanca
Int64Index([193051], dtype='int64')
327338
2021 38 Santa Cruz de Tenerife
Int64Index([198001], dtype='int64')
1044405
2021 39 Cantabria
Int64Index([69301], dtype='int64')
584507
2021 40 Segovia
Int64Index([202951], dtype='int64')
153663
2021 41 Sevilla
Int64Index([207901], dtype='int64')
1947852
2021 42 Soria
Int64Index([212851], dtype='int64')
88747
2021 43 Tarragona
Int64Index([217801], dtype='int64')
822309
2021 44 Teruel
Int64Index([222751], dtype='int64')
134545
2021 45 Toledo
Int64Index([227701], dtype='int64')
709403
2021 46 Valencia/València
Int64Index([232651], dtype='int64')
2589312
2021 47 Valladolid
Int64Index([237601], dtype='int64')
519361
2021 48 Bizkaia
Int64Index([49501], dtype='int64')
1154334
2021 49 Zamora
Int64Index([242551], dtype='int64')
168725
2021 50 Zaragoza
Int64Index([247501], dtype='int64')
967452
2021 51 Ceuta
Int64Index([252451], dtype='int64')
83517
2021 52 Melilla
Int64Index([257401], dtype='int64')
86261
2021 TOTAL ESPAÑA
Int64Index([1], dtype='int64')
47385107
2022 01 Araba/Álava
Int64Index([19800], dtype='int64')
334412
2022 02 Albacete
Int64Index([4950], dtype='int64')
385727
2022 03 Alicante/Alacant
Int64Index([9900], dtype='int64')
1901594
2022 04 Almería
Int64Index([14850], dtype='int64')
740534
2022 05 Ávila
Int64Index([29700], dtype='int64')
158140
2022 06 Badajoz
Int64Index([34650], dtype='int64')
666971
2022 07 Balears, Illes
Int64Index([39600], dtype='int64')
1176659
2022 08 Barcelona
Int64Index([44550], dtype='int64')
5727615
2022 09 Burgos
Int64Index([54450], dtype='int64')
355045
2022 10 Cáceres
Int64Index([59400], dtype='int64')
387805
2022 11 Cádiz
Int64Index([64350], dtype='int64')
1246781
2022 12 Castellón/Castelló
Int64Index([74250], dtype='int64')
590616
2022 13 Ciudad Real
Int64Index([79200], dtype='int64')
490806
2022 14 Córdoba
Int64Index([84150], dtype='int64')
772464
2022 15 Coruña, A
Int64Index([89100], dtype='int64')
1119180
2022 16 Cuenca
Int64Index([94050], dtype='int64')
195215
2022 17 Girona
Int64Index([103950], dtype='int64')
793478
2022 18 Granada
Int64Index([108900], dtype='int64')
921987
2022 19 Guadalajara
Int64Index([113850], dtype='int64')
268127
2022 20 Gipuzkoa
Int64Index([99000], dtype='int64')
724418
2022 21 Huelva
Int64Index([118800], dtype='int64')
528763
2022 22 Huesca
Int64Index([123750], dtype='int64')
225456
2022 23 Jaén
Int64Index([128700], dtype='int64')
623761
2022 24 León
Int64Index([133650], dtype='int64')
448179
2022 25 Lleida
Int64Index([138600], dtype='int64')
441443
2022 26 Rioja, La
Int64Index([188100], dtype='int64')
319892
2022 27 Lugo
Int64Index([143550], dtype='int64')
323989
2022 28 Madrid
Int64Index([148500], dtype='int64')
6750336
2022 29 Málaga
Int64Index([153450], dtype='int64')
1717504
2022 30 Murcia
Int64Index([158400], dtype='int64')
1531878
2022 31 Navarra
Int64Index([163350], dtype='int64')
664117
2022 32 Ourense
Int64Index([168300], dtype='int64')
304280
2022 33 Asturias
Int64Index([24750], dtype='int64')
1004686
2022 34 Palencia
Int64Index([173250], dtype='int64')
158008
2022 35 Palmas, Las
Int64Index([178200], dtype='int64')
1129395
2022 36 Pontevedra
Int64Index([183150], dtype='int64')
943015
2022 37 Salamanca
Int64Index([193050], dtype='int64')
325898
2022 38 Santa Cruz de Tenerife
Int64Index([198000], dtype='int64')
1048306
2022 39 Cantabria
Int64Index([69300], dtype='int64')
585402
2022 40 Segovia
Int64Index([202950], dtype='int64')
153803
2022 41 Sevilla
Int64Index([207900], dtype='int64')
1948393
2022 42 Soria
Int64Index([212850], dtype='int64')
88377
2022 43 Tarragona
Int64Index([217800], dtype='int64')
830075
2022 44 Teruel
Int64Index([222750], dtype='int64')
134421
2022 45 Toledo
Int64Index([227700], dtype='int64')
713453
2022 46 Valencia/València
Int64Index([232650], dtype='int64')
2605757
2022 47 Valladolid
Int64Index([237600], dtype='int64')
517975
2022 48 Bizkaia
Int64Index([49500], dtype='int64')
1149344
2022 49 Zamora
Int64Index([242550], dtype='int64')
167215
2022 50 Zaragoza
Int64Index([247500], dtype='int64')
966438
2022 51 Ceuta
Int64Index([252450], dtype='int64')
83117
2022 52 Melilla
Int64Index([257400], dtype='int64')
85170
2022 TOTAL ESPAÑA
Int64Index([0], dtype='int64')
47475420

In [8]:
censo2023 = pd.read_csv('./Inputs/Censo_CCAA_Provincias.csv', header=0, delimiter = ';')
censo2023

,Total Nacional,Comunidades y Ciudades Autónomas,Provincias,Sexo,Año,Total
0,Total Nacional,NaN,NaN,Ambos sexos,2023,48.085.361
1,Total Nacional,NaN,NaN,Ambos sexos,2022,47.486.727
2,Total Nacional,NaN,NaN,Ambos sexos,2021,47.400.798
3,Total Nacional,NaN,NaN,Hombre,2023,23.565.593
4,Total Nacional,NaN,NaN,Hombre,2022,23.288.747
...,...,...,...,...,...,...
643,Total Nacional,19 Melilla,52 Melilla,Hombre,2022,42.978
644,Total Nacional,19 Melilla,52 Melilla,Hombre,2021,43.823
645,Total Nacional,19 Melilla,52 Melilla,Mujer,2023,42.331
646,Total Nacional,19 Melilla,52 Melilla,Mujer,2022,41.954
647,Total Nacional,19 Melilla,52 Melilla,Mujer,2021,42.627

In [9]:
aux = []
for provincia in provincias:
    #print (provincia)
    if provincia == 'TOTAL ESPAÑA': 
        continue
    row = censo2023[(censo2023['Provincias'] == provincia) & (censo2023['Año'] == 2023) & (censo2023['Sexo'] == 'Ambos sexos')].index
    #print (row)
    aux1 = censo2023['Total'][row[0]].replace('.', '')
    #print (aux1)
    aux.append(int(aux1))
aux.append(int(censo2023['Total'][0].replace('.', '')))
poblaciones['2023'] = aux
#poblaciones

In [10]:
codigos = []

for i, provincia in enumerate(provincias):
    if provincia == 'TOTAL ESPAÑA': 
        continue
    codigos.append(provincia[:2])
    provincias[i] = provincia[3:]

codigos.append('00')
codigos

['01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '00']

In [11]:
coordenadas = pd.read_csv('./Inputs/Coordenadas_provincias.csv', header = 0, delimiter = ';')
coordenadas

,Geo Point,Geo Shape,CCAA,Cod_CCAA,Provincia,Texto,Codigo
0,"40.2413705852, -0.146777086937","{""coordinates"": [[[[0.688666451482042, 39.9004...",Comunitat Valenciana,10,Castelló,Castellón,12
1,"37.5771794021, -6.82930221031","{""coordinates"": [[[-6.927226499279804, 38.2044...",Andalucía,1,Huelva,Huelva,21
2,"28.3125567678, -17.017856743","{""coordinates"": [[[[-17.925108281249873, 27.84...",Canarias,5,Santa Cruz de Tenerife,Santa Cruz de Tenerife,38
3,"40.5710367492, -4.94553505619","{""coordinates"": [[[-5.01385768137012, 41.16424...",Castilla y León,7,Ávila,Ávila,5
4,"36.5538729195, -5.7604183752","{""coordinates"": [[[[-5.437333022160619, 36.064...",Andalucía,1,Cádiz,Cádiz,11
5,"39.3702562375, -0.800789615081","{""coordinates"": [[[[-0.987141629168891, 39.980...",Comunitat Valenciana,10,València,Valencia,46
6,"40.8134495654, -2.62368878371","{""coordinates"": [[[[-3.374050970979573, 40.640...",Castilla - La Mancha,8,Guadalajara,Guadalajara,19
7,"42.3718338546, -4.53585717538","{""coordinates"": [[[[-4.071987588784325, 42.165...",Castilla y León,7,Palencia,Palencia,34
8,"41.1710254065, -4.05415057783","{""coordinates"": [[[-3.963827913293567, 41.5860...",Castilla y León,7,Segovia,Segovia,40
9,"41.7271743961, -5.98053925522","{""coordinates"": [[[-6.761139055177893, 42.2398...",Castilla y León,7,Zamora,Zamora,49
10,"40.4950873744, -3.71704619215","{""coordinates"": [[[[-4.254107365433731, 40.658...",Comunidad de Madrid,13,Madrid,Madrid,28
11,"43.1975220484, -4.03002122038","{""coordinates"": [[[[-3.263816261742692, 43.265...",Cantabria,6,Cantabria,Cantabria,39
12,"43.2376797057, -2.85260007926","{""coordinates"": [[[[-3.028631798416118, 43.044...",País Vasco,16,Bizkaia,Vizcaya,48
13,"38.7097707381, -6.14158521981","{""coordinates"": [[[-4.677889020055496, 39.4348...",Extremadura,11,Badajoz,Badajoz,6
14,"42.2030557371, -0.0728865943582","{""coordinates"": [[[-0.747266240683383, 42.9223...",Aragón,2,Huesca,Huesca,22
15,"43.011764, -7.44638404764","{""coordinates"": [[[[-7.076086210906103, 43.555...",Galicia,12,Lugo,Lugo,27
16,"41.6207742504, -2.58874304739","{""coordinates"": [[[-2.344003620036013, 42.1455...",Castilla y León,7,Soria,Soria,42
17,"39.7937341614, -4.14815562595","{""coordinates"": [[[-4.373200998592973, 40.3142...",Castilla - La Mancha,8,Toledo,Toledo,45
18,"39.5751889864, 2.91229172079","{""coordinates"": [[[[4.093964552869251, 40.0883...",Illes Balears,4,Illes Balears,Islas Baleares,7
19,"42.6672011509, -1.64611414443","{""coordinates"": [[[[-1.147643003840329, 42.441...",Comunidad Foral de Navarra,15,Navarra,Navarra,31
20,"41.7310008895, 1.98405401772","{""coordinates"": [[[[1.657073101107445, 42.1144...",Cataluña,9,Barcelona,Barcelona,8
21,"39.8960496846, -2.19567153274","{""coordinates"": [[[-2.152110668965416, 40.6576...",Castilla - La Mancha,8,Cuenca,Cuenca,16
22,"38.8254086192, -1.98037326935","{""coordinates"": [[[-1.483656580918969, 39.4182...",Castilla - La Mancha,8,Albacete,Albacete,2
23,"39.7118899607, -6.16082194997","{""coordinates"": [[[-6.230474872455294, 40.4866...",Extremadura,11,Cáceres,Cáceres,10
24,"38.9256128254, -3.82809764894","{""coordinates"": [[[[-4.76775930538213, 39.5156...",Castilla - La Mancha,8,Ciudad Real,Ciudad Real,13
25,"42.0439686698, 1.04798206104","{""coordinates"": [[[[1.715645891516689, 41.8921...",Cataluña,9,Lleida,Lleida,25
26,"38.4786378049, -0.568699068376","{""coordinates"": [[[[-0.485462499104892, 38.165...",Comunitat Valenciana,10,Alacant,Alicante,3
27,"38.0023681653, -1.48575629332","{""coordinates"": [[[[-1.54668694559277, 37.4073...",Región de Murcia,14,Murcia,Murcia,30
28,"37.9926944409, -4.80926161095","{""coordinates"": [[[[-5.081139913319542, 37.646...",Andalucía,1,Córdoba,Córdoba,14
29,"42.6199552439, -5.83988102629","{""coordinates"": [[[-4.893432037985476, 43.2384...",Castilla y León,7,León,León,24
30,"38.0165122783, -3.44169215171","{""coordinates"": [[[-2.766827131575509, 38.5329...",Andalucía,1,Jaén,Jaén,23
31,"42.3687127267, -3.58574245567","{""coordinates"": [[[[-2.934887275101909, 42.594...",Castilla y León,7,Burgos,Burgos,9
32,"43.1437759117, -2.19417845709","{""coordinates"": [[[[-1.998025182427766, 43.322...",País Vasco,16,Gipuzcoa,Guipúzcoa,20
33,"40.8049892162, -6.06541224773","{""coordinates"": [[[-6.475918255338319, 41.2873...",Castilla y León,7,Salamanca,Salamanca,37
34,"35.2908279949, -2.95053552337","{""coordinates"": [[[-2.952535036387899, 35.3200...",Melilla,19,Melilla,Melilla,52
35,"37.4356699135, -5.68277303032","{""coordinates"": [[[-5.725075864605317, 38.1957...",Andalucía,1,Sevilla,Sevilla,41
36,"41.6341260695, -4.84719141141","{""coordinates"": [[[[-5.516732151072739, 42.093...",Castilla y León,7,Valladolid,Valladolid,47
37,"35.8934069863, -5.34342403891","{""coordinates"": [[[-5.367106021081503, 35.9175...",Ceuta,18,Ceuta,Ceuta,51
38,"36.8138591651, -4.72586195603","{""coordinates"": [[[-4.406576081191073, 37.2741...",Andalucía,1,Málaga,Málaga,29
39,"42.1964503002, -7.59259790937","{""coordinates"": [[[-7.920549280708581, 42.5666...",Galicia,12,Ourense,Orense,32
40,"41.0876143957, 0.818127863314","{""coordinates"": [[[[0.852078841098488, 40.7251...",Cataluña,9,Tarragona,Tarragona,43
41,"42.8351264353, -2.72060346921","{""coordinates"": [[[-3.026794053753935, 43.2166...",País Vasco,16,Araba,Álava,1
42,"42.1280117119, 2.6735559327","{""coordinates"": [[[[2.792737760435918, 41.6706...",Cataluña,9,Girona,Gerona,17
43,"37.1960852121, -2.3448128003","{""coordinates"": [[[[-2.19104266702894, 36.7200...",Andalucía,1,Almería,Almería,4
44,"37.3125169672, -3.26788107732","{""coordinates"": [[[[-3.389706288728371, 36.708...",Andalucía,1,Granada,Granada,18
45,"42.2748706958, -2.5170441194","{""coordinates"": [[[-2.997229851864886, 42.6421...","Rioja, La",17,La Rioja,La Rioja,26
46,"28.3624928216, -14.5509933924","{""coordinates"": [[[[-15.41958271571381, 28.180...",Canarias,5,Las Palmas,Las Palmas,35
47,"42.435764706, -8.46106294738","{""coordinates"": [[[[-8.936459570853652, 42.349...",Galicia,12,Pontevedra,Pontevedra,36
48,"43.1257958229, -8.4642836868","{""coordinates"": [[[[-9.015034632124795, 42.485...",Galicia,12,A Coruña,La Coruña,15
49,"40.6612619615, -0.815532258446","{""coordinates"": [[[-0.558551073640885, 41.3538...",Aragón,2,Teruel,Teruel,44
50,"41.6203648019, -1.06449678144","{""coordinates"": [[[-0.915798877388363, 42.7438...",Aragón,2,Zaragoza,Zaragoza,50
51,"43.292357861, -5.99350932547","{""coordinates"": [[[-5.839882173983647, 43.6612...","Asturias, Principado de",3,Asturias,Asturias,33

In [12]:
def weighted_coord (lat,long,poblacion):
    auxpob = poblacion['2023'][:-1]
    auxlat = [c*w for c,w in zip(lat,auxpob)]
    auxlong = [c*w for c,w in zip(long,auxpob)]
    return sum(auxlat)/sum(auxpob),sum(auxlong)/sum(auxpob)

In [13]:
lat, long = [], []
for cod in codigos:
    if cod == '00':
        lat00,long00 = weighted_coord(lat,long,poblaciones)
        print (np.mean(lat), lat00, np.mean(long), long00)
        lat.append(lat00)
        long.append(long00)
    else:
        row = coordenadas[coordenadas['Codigo'] == int (cod)].index
        #print (row)
        indice = coordenadas['Geo Point'][row[0]].find(',')
        #print (indice)
        auxlat = float (coordenadas['Geo Point'][row[0]][:indice])
        auxlong = float (coordenadas['Geo Point'][row[0]][indice+1:])
        #print (auxlat, auxlong)
        lat.append(auxlat)
        long.append(auxlong)

39.94960989031154 39.69511858365859 -3.8346275171995043 -3.2020228170909313

In [14]:
poblacion_provincias = pd.DataFrame()
poblacion_provincias ['Codigos'] = codigos
poblacion_provincias ['Provincias'] = provincias

poblacion_provincias ['Latitud'] = lat
poblacion_provincias ['Longitud'] = long

for año in range (2014,2024):
    poblacion_provincias[str(año)] = poblaciones[str(año)]
    
poblacion_provincias

,Codigos,Provincias,Latitud,Longitud,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,01,Araba/Álava,42.835126,-2.720603,321932,323648,324126,326574,328868,331549,333940,333626,334412,336308
1,02,Albacete,38.825409,-1.980373,396987,394580,392118,390032,388786,388167,388270,386464,385727,387529
2,03,Alicante/Alacant,38.478638,-0.568699,1868438,1855047,1836459,1825332,1838819,1858683,1879888,1881762,1901594,1955268
3,04,Almería,37.196085,-2.344813,701688,701211,704297,706672,709340,716820,727945,731792,740534,753364
4,05,Ávila,40.571037,-4.945535,167015,164925,162514,160700,158498,157640,157664,158421,158140,159764
5,06,Badajoz,38.709771,-6.141585,690929,686730,684113,679884,676376,673559,672137,669943,666971,666049
6,07,"Balears, Illes",39.575189,2.912292,1103442,1104479,1107220,1115999,1128908,1149460,1171543,1173008,1176659,1209906
7,08,Barcelona,41.731001,1.984054,5523784,5523922,5542680,5576037,5609350,5664579,5743402,5714730,5727615,5797356
8,09,Burgos,42.368713,-3.585742,366900,364002,360995,358171,357070,356958,357650,356055,355045,357370
9,10,Cáceres,39.711890,-6.160822,408703,406267,403665,400036,396487,394151,391850,389558,387805,388257
10,11,Cádiz,36.553873,-5.760418,1240175,1240284,1239889,1239435,1238714,1240155,1244049,1245960,1246781,1254866
11,12,Castellón/Castelló,40.241371,-0.146777,587508,582327,579245,575470,576898,579962,585590,587064,590616,604086
12,13,Ciudad Real,38.925613,-3.828098,519613,513713,506888,502578,499100,495761,495045,492591,490806,491927
13,14,Córdoba,37.992694,-4.809262,799402,795611,791610,788219,785240,782979,781451,776789,772464,775002
14,15,"Coruña, A",43.125796,-8.464284,1132735,1127196,1122799,1120294,1119351,1119596,1121815,1120134,1119180,1123884
15,16,Cuenca,39.896050,-2.195672,207449,203841,201071,198718,197222,196329,196139,195516,195215,198436
16,17,Girona,42.128012,2.673556,756156,753054,753576,755716,761947,771044,781788,786596,793478,808672
17,18,Granada,37.312517,-3.267881,919455,917297,915392,912938,912075,914678,919168,921338,921987,934072
18,19,Guadalajara,40.813450,-2.623689,255426,253686,252882,253310,254308,257762,261995,265588,268127,275082
19,20,Gipuzkoa,43.143776,-2.194178,715148,716834,717832,719282,720592,723576,727121,726033,724418,726712
20,21,Huelva,37.577179,-6.829302,519229,520017,519596,518930,519932,521870,524278,525835,528763,534084
21,22,Huesca,42.203056,-0.072887,224909,222909,221079,219702,219345,220461,222687,224264,225456,226878
22,23,Jaén,38.016512,-3.441692,659033,654170,648250,643484,638099,633564,631381,627190,623761,620637
23,24,León,42.619955,-5.839881,484694,479395,473604,468316,463746,460001,456439,451706,448179,448573
24,25,Lleida,42.043969,1.047982,438001,436029,434041,432384,432866,434930,438517,439727,441443,447343
25,26,"Rioja, La",42.274871,-2.517044,319002,317053,315794,315381,315675,316798,319914,319796,319892,322282
26,27,Lugo,43.011764,-7.446384,342748,339386,336527,333634,331327,329587,327946,326013,323989,324267
27,28,Madrid,40.495087,-3.717046,6454440,6436996,6466996,6507184,6578079,6663394,6779888,6751251,6750336,6871903
28,29,Málaga,36.813859,-4.725862,1621968,1628973,1629298,1630615,1641121,1661785,1685920,1695651,1717504,1752728
29,30,Murcia,38.002368,-1.485756,1466818,1467288,1464847,1470273,1478509,1493898,1511251,1518486,1531878,1551692
30,31,Navarra,42.667201,-1.646114,640790,640476,640647,643234,647554,654214,661197,661537,664117,672155
31,32,Ourense,42.196450,-7.592598,322293,318391,314853,311680,309293,307651,306650,305223,304280,304563
32,33,Asturias,43.292358,-5.993509,1061756,1051229,1042608,1034960,1028244,1022800,1018784,1011792,1004686,1006060
33,34,Palencia,42.371834,-4.535857,167609,166035,164644,163390,162035,160980,160321,159123,158008,157787
34,35,"Palmas, Las",28.362493,-14.550993,1100027,1098406,1097800,1100480,1109175,1120406,1131065,1128539,1129395,1145843
35,36,Pontevedra,42.435765,-8.461063,950919,947374,944346,942731,941772,942665,945408,944275,943015,946710
36,37,Salamanca,40.804989,-6.065412,342459,339395,335985,333603,331473,330119,329245,327338,325898,327089
37,38,Santa Cruz de Tenerife,28.312557,-17.017857,1004788,1001900,1004124,1007641,1018510,1032983,1044887,1044405,1048306,1067173
38,39,Cantabria,43.197522,-4.030021,588656,585179,582206,580295,580229,581078,582905,584507,585402,588387
39,40,Segovia,41.171025,-4.054151,159303,157570,155652,154184,153342,153129,153478,153663,153803,155332
40,41,Sevilla,37.435670,-5.682773,1941355,1941480,1939775,1939527,1939887,1942389,1950219,1947852,1948393,1959394
41,42,Soria,41.620774,-2.588743,92221,91006,90040,88903,88600,88636,88884,88747,88377,89528
42,43,Tarragona,41.087614,0.818128,800962,795101,792299,791693,795902,804664,816772,822309,830075,848592
43,44,Teruel,40.661262,-0.815532,140365,138932,136977,135562,134572,134137,134176,134545,134421,135046
44,45,Toledo,39.793734,-4.148156,699136,693371,688672,686841,687391,694844,703772,709403,713453,731112
45,46,Valencia/València,39.370256,-0.800790,2548898,2543315,2544264,2540707,2547986,2565124,2591875,2589312,2605757,2656841
46,47,Valladolid,41.634126,-4.847191,529157,526288,523679,521130,519851,519546,520649,519361,517975,521333
47,48,Bizkaia,43.237680,-2.852600,1151905,1148775,1147576,1148302,1149628,1152651,1159443,1154334,1149344,1153282
48,49,Zamora,41.727174,-5.980539,185432,183436,180406,177404,174549,172539,170588,168725,167215,166927
49,50,Zaragoza,41.620365,-1.064497,960111,956006,950507,953486,954811,964693,972528,967452,966438,979365
50,51,Ceuta,35.893407,-5.343424,84963,84263,84519,84959,85144,84777,84202,83517,83117,83052
51,52,Melilla,35.290828,-2.950536,84509,85584,86026,86120,86384,86487,87076,86261,85170,85493
52,00,TOTAL ESPAÑA,39.695119,-3.202023,46771341,46624382,46557008,46572132,46722980,47026208,47450795,47385107,47475420,48085361

In [15]:
poblacion_provincias.to_csv('Cities_unified.csv', index=False)